.DEFAULT_GOAL := help
SHELL := /bin/sh

## help: list available targets
help:
	@grep -E '^## ' $(MAKEFILE_LIST) | sed 's/## //'

## install: install all backend + frontend + tooling dependencies
install:
	pnpm install
	cd backend && python -m pip install -e ".[dev]"

## dev: start the full stack (PostGIS + API + web) with hot reload
dev:
	docker compose up --build

## db: start only PostGIS (useful when running API/web natively)
db:
	docker compose up -d db

## migrate: apply all database migrations
migrate:
	cd backend && alembic upgrade head

## migration: create a new autogenerated migration -- make migration m="add x"
migration:
	cd backend && alembic revision --autogenerate -m "$(m)"

## seed: load the demo dataset (user, projects, sites, metric time series)
seed:
	cd backend && python -m app.db.seed

## test: run the full test suite (backend + frontend)
test: test-backend test-frontend

## test-backend: run pytest with coverage
test-backend:
	cd backend && python -m pytest

## test-frontend: run vitest with coverage
test-frontend:
	pnpm --filter darukaa-web test:coverage

## lint: run every linter and type checker
lint:
	cd backend && python -m ruff check . && python -m ruff format --check . && python -m mypy app
	pnpm --filter darukaa-web lint
	pnpm --filter darukaa-web typecheck
	pnpm format:check

## format: auto-fix formatting across the repo
format:
	cd backend && python -m ruff check --fix . && python -m ruff format .
	pnpm format

## clean: remove build artefacts and caches
clean:
	rm -rf frontend/dist frontend/coverage backend/htmlcov backend/.coverage
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	find . -type d -name .pytest_cache -prune -exec rm -rf {} +

.PHONY: help install dev db migrate migration seed test test-backend test-frontend lint format clean
